version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: "pdf_summarizer"
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./pdfs:/code/pdfs:ro
      - ./app:/code/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_API_URL=${OLLAMA_API_URL:-http://ollama:11434}
    depends_on:
      - ollama
    networks:
      - llm_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_template
    pull_policy: always
    tty: true
    restart: on-failure
    ports:
      - 11434:11434
    volumes:
      - ./ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/entrypoint.sh
    environment:
      - 'OLLAMA_MAX_LOADED_MODELS=4'
      - 'OLLAMA_NUM_PARALLEL=1'
      - 'OLLAMA_KEEP_ALIVE=-1'
    entrypoint: ["/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 10G
    networks:
      - llm_network

networks:
  llm_network:
    driver: bridge

volumes:
  ollama_data: